config/routes.rb
Rails.application.routes.draw do

  # USERS MANAGEMENT
  devise_for :users
  post '/users', to: 'users#create'
  get '/users/expired', to: 'users#list_expired'

  resources :users

  # FILTERS
  resources :filters
  # TELESCOPES
  resources :telescopes
  # EYEPIECES
  resources :eyepieces
  # BINOCULARS
  resources :binoculars

  # CELESTIAL BODIES
  resources :celestial_bodies

  # OBSERVATIVE SESSIONS
  resources :observative_sessions

  root to: 'application#index'

end

app/models/observative_session.rb
# == Schema Information
#
# Table name: observative_sessions
#
#  id               :integer          not null, primary key
#  name             :string
#  category         :integer
#  start            :datetime
#  end              :datetime
#  antoniadi        :integer
#  pickering        :integer
#  sky_transparency :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  user_id          :integer
#

#
# Classe modello per la tabella "observative_sessions".
#
class ObservativeSession < ApplicationRecord

  # relazioni
  belongs_to :user
  has_many :observations, dependent: :destroy

end

app/controllers/observative_sessions_controller.rb
#
# Classe controller che implementa le funzionalità CRUD per la 
# classe model "ObservativeSession".
#
class ObservativeSessionsController < ApplicationController
  before_action :set_observative_session, only: [:show, :edit, :update, :destroy]

  # Metodo che recupera le sessioni osservative (eventualmente mediante ricerca), 
  # le ordina, attua una paginazione delle stesse ed in seguito
  # le visualizza.
  def index
    @q = ObservativeSession.ransack(params[:q])
    @observative_sessions = @q.result.order(params[:order]).paginate(page: params[:page]) if params[:q].present?
    @observative_sessions = ObservativeSession.order(params[:orser]).paginate(page: params[:page]) unless params[:q].present?
  end

  # Metodo ereditato dalla classe ApplicationController.
  def show
    @observations = @observative_session.observations
    @user = @observative_session.user
  end

  # Metodo che crea un'istanza di ObservativeSession, la quale verrà 
  # passata alla vista corrispondente all'URL "/observative_sessions/1/edit".
  def new
    @observative_session = ObservativeSession.new
  end

  # Metodo ereditato dalla classe ApplicationController.
  def edit
  end

  # Questo metodo crea un'istanza di ObservativeSession e la salva nel database.
  # Se l'operazione si conclude con successo, avverrà una redirezione alla pagina
  # che presenta i dettagli della sessione osservativa. In caso contrario, verrà
  # visualizzato un messaggio d'errore.
  def create
    @observative_session = ObservativeSession.new(observative_session_params)

    respond_to do |format|
      if @observative_session.save
        format.html { redirect_to @observative_session, notice: 'Observative session was successfully created.' }
        format.json { render :show, status: :created, location: @observative_session }
      else
        format.html { render :new }
        format.json { render json: @observative_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # Metodo che aggiorna un'istanza di ObservativeSession. Se l'operazione avviene con successo,
  # avverrà una redirezione alla pagina che visualizza i dettagli della sessione osservativa.
  # In caso contrario, verrà visualizzato un messaggio d'errore.
  def update
    respond_to do |format|
      if @observative_session.update(observative_session_params)
        format.html { redirect_to @observative_session, notice: 'Observative session was successfully updated.' }
        format.json { render :show, status: :ok, location: @observative_session }
      else
        format.html { render :edit }
        format.json { render json: @observative_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # Metodo che elimina un'istanza di ObservativeSession. Se l'operazione avviene con
  # successo, il browser verrà redirezionato alla lista delle sessioni osservative.
  def destroy
    @observative_session.destroy
    respond_to do |format|
      format.html { redirect_to observative_sessions_url, notice: 'Observative session was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_observative_session
      @observative_session = ObservativeSession.find(params[:id])
    end

    # Metodo che imposta i parametri richiesti e ammessi durante la creazione o la modifica
    # di un'istanza di ObservativeSession.
    def observative_session_params
      params.require(:observative_session).permit(:name, :category, :start, :end, :antoniadi, :pickering, :sky_transparency)
    end
end

app/helpers/observative_sessions_helper.rb
module ObservativeSessionsHelper
end

app/views/observative_sessions/_form.html.erb
<%= form_with(model: observative_session, local: true) do |form| %>
  <% if observative_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(observative_session.errors.count, "error") %> prohibited this observative_session from being saved:</h2>

      <ul>
      <% observative_session.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :observative_session_name %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.number_field :category, id: :observative_session_category %>
  </div>

  <div class="field">
    <%= form.label :start %>
    <%= form.datetime_select :start, id: :observative_session_start %>
  </div>

  <div class="field">
    <%= form.label :end %>
    <%= form.datetime_select :end, id: :observative_session_end %>
  </div>

  <div class="field">
    <%= form.label :antoniadi %>
    <%= form.number_field :antoniadi, id: :observative_session_antoniadi %>
  </div>

  <div class="field">
    <%= form.label :pickering %>
    <%= form.number_field :pickering, id: :observative_session_pickering %>
  </div>

  <div class="field">
    <%= form.label :sky_transparency %>
    <%= form.number_field :sky_transparency, id: :observative_session_sky_transparency %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/observative_sessions/_observations_list.html.erb
<div class="row">
  <div class="col-sm-12">
    <table class="table">
      <thead>
        <tr>
          <th>Oss. nr.</th>
          <th>Descrizione</th>
          <th>Ora inizio</th>
          <th>Stato</th>
          <th>Oggetto celeste</th>
          <th>Note</th>
        </tr>
      </thead>
      <tbody>
        <% @observations.each_with_index do |ob, i| %>
          <tr>
            <td>#<%= i + 1 %></td>
            <td><%= ob.description %></td>
            <td><%= ob.start_time.strftime "%d/%m/%Y %H:%M" %></td>
            <td><span class="label label-default"><%= ob.completed ? "COMPLETATA" : "NON EFFETTUATA" %></span></td>
            <td><%= link_to ob.celestial_body.name, celestial_body_path(ob.celestial_body) %></td>
            <td><%= ob.notes %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/observative_sessions/edit.html.erb
<h1>Editing Observative Session</h1>

<%= render 'form', observative_session: @observative_session %>

<%= link_to 'Show', @observative_session %> |
<%= link_to 'Back', observative_sessions_path %>

app/views/observative_sessions/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title">Lista Sessioni Osservative</h1>
  </div>
  <div class="panel-body">
    <%= search_form_for @q, { id: '' } do |f| %>
      <div class="row">
        <div class="col-sm-4">
          <div class="form-group">
            <%= f.label 'Cerca per nome' %>
            <%= f.search_field :name_cont, class: 'form-control' %>
          </div>
        </div>
        <div class="col-sm-2 col-sm-offset-6">
          <div class="form-group">
            <label for="order">Ordina risultati per</label>
            <%= select_tag 'order', options_for_select([['Nessuno',''], ['Nome', 'name'], ['Categoria','category'], ['Inizio', 'start'], ['Fine', 'end'], ['Antoniadi', 'antoniadi'], ['Pickering', 'pickering']], params[:order] || ''), class: 'form-control', onchange: "$('#observative_session_search').submit();" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Inizio</th>
        <th>Scala Antoniadi</th>
        <th>Scala Pickering</th>
        <th>Trasparenza del cielo</th>
        <th colspan="3">Azioni</th>
      </tr>
    </thead>

    <tbody>
      <% @observative_sessions.each do |observative_session| %>
        <tr>
          <td><%= observative_session.name %></td>
          <td><%= observative_session.start.strftime "%d/%m/%Y" %></td>
          <td><%= observative_session.antoniadi %></td>
          <td><%= observative_session.pickering %></td>
          <td><%= observative_session.sky_transparency %></td>
          <td><%= link_to 'Visualizza', observative_session %></td>
          <td><%= link_to 'Modifica', edit_observative_session_path(observative_session) %></td>
          <td><%= link_to 'Elimina', observative_session, method: :delete, data: { confirm: 'Sei sicuro?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <span><center><%= will_paginate @observative_session, previous_label: 'Precedente', next_label: 'Successivo' %></center></span>
</div>

app/views/observative_sessions/new.html.erb
<h1>New Observative Session</h1>

<%= render 'form', observative_session: @observative_session %>

<%= link_to 'Back', observative_sessions_path %>

app/views/observative_sessions/show.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-default">
      <div class="panel-heading"><div class="clearfix"><h2 class="h3 pull-left"><%= @observative_session.name %></h2><div class="pull-right"><%= link_to 'Torna alla lista di sessioni osservative', observative_sessions_path %></div></div></div>
      <div class="panel-body">
        <h3 class="h4">Informazioni sessione</h3>
        <p>
          <strong>Sessione osservativa effettuata da:</strong>
          <%= link_to @user.name + " " + @user.surname, user_path(@user) %>
        </p>
        <p>
          <strong>Inizio:</strong>
          <%= @observative_session.start.strftime "%d/%m/%Y %H:%M" %>
        </p>
        <p>Seeing astronomico</p>
        <p>
          <strong>Scala Antoniadi:</strong>
          <%= @observative_session.antoniadi %>
        </p>
        <p>
          <strong>Pickering:</strong>
          <%= @observative_session.pickering %>
        </p>
        <p>
          <strong>Trasparenza cielo:</strong>
          <%= @observative_session.sky_transparency %>
        </p>
        <hr>
        <h3 class="h4">Osservazioni della sessione</h3>
        <%= render 'observations_list' %>
      </div>
  </div>
</div>