config/routes.rb
Rails.application.routes.draw do

  # USERS MANAGEMENT
  devise_for :users
  post '/users', to: 'users#create'
  get '/users/expired', to: 'users#list_expired'

  resources :users

  # FILTERS
  resources :filters
  # TELESCOPES
  resources :telescopes
  # EYEPIECES
  resources :eyepieces
  # BINOCULARS
  resources :binoculars

  # CELESTIAL BODIES
  resources :celestial_bodies

  # OBSERVATIVE SESSIONS
  resources :observative_sessions

  root to: 'application#index'

end

app/views/layouts/_admin_navbar.html.erb
<nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "STELLAR1", root_path, class: 'navbar-brand' %>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Utenti <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Tutti", root_path %></li>
                  <li><%= link_to "Tessere scadute", users_expired_path %></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Strumenti <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Binocoli", binoculars_path %></li>
                  <li><%= link_to "Oculari", eyepieces_path %></li>
                  <li><%= link_to "Filtri", filters_path %></li>
                  <li><%= link_to "Telescopi", telescopes_path %></li>
                </ul>
              </li>
              <li>
                <%= link_to "Corpi Celesti", celestial_bodies_path %>
              </li>
              <li>
                <%= link_to "Sessioni osservative", observative_sessions_path %>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

app/views/layouts/_user_navbar.html.erb
<nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "STELLAR1", root_path, class: 'navbar-brand' %>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Azioni <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Tutti", root_path %></li>
                  <li><%= link_to "Tessere scadute", users_expired_path %></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Strumenti <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Binocoli", binoculars_path %></li>
                  <li><%= link_to "Oculari", eyepieces_path %></li>
                  <li><%= link_to "Filtri", filters_path %></li>
                  <li><%= link_to "Telescopi", telescopes_path %></li>
                </ul>
              </li>
              <li>
                <%= link_to "Corpi Celesti", celestial_bodies_path %>
              </li>
              <li>
                <%= link_to "Sessioni osservative", observative_sessions_path %>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stellar1</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/admin_navbar' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/default.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stellar1</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stellar1</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/user_navbar' %>
      <%= yield %>
    </div>
  </body>
</html>